sudo: false
language: python
python:
  -3.6
  -3.7
  -3.8
before_install:
  pip install pipenv
install: 
  pipenv install --dev
before_script:
  -export FLASK_APP=$TRAVIS_BUILD_DIR/app.py
  -export FLASK_DEBUG=1
script: flask test